# Generated by Django 6.0.1 on 2026-02-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email адрес"),
                ),
                (
                    "is_valid_syntax",
                    models.BooleanField(
                        default=False, verbose_name="Валидный синтаксис"
                    ),
                ),
                (
                    "has_mx_record",
                    models.BooleanField(default=False, verbose_name="Есть MX-запись"),
                ),
                (
                    "is_deliverable",
                    models.BooleanField(default=False, verbose_name="Доставляемый"),
                ),
                (
                    "is_disposable",
                    models.BooleanField(
                        default=False, verbose_name="Одноразовый email"
                    ),
                ),
                (
                    "domain",
                    models.CharField(blank=True, max_length=255, verbose_name="Домен"),
                ),
                ("mx_records", models.TextField(blank=True, verbose_name="MX-записи")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Сообщение об ошибке"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "Проверка email",
                "verbose_name_plural": "Проверки email",
                "ordering": ["-created_at"],
            },
        ),
    ]
