# Generated by Django 6.0.1 on 2026-02-03 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("free", "Бесплатный"),
                            ("basic", "Базовый"),
                            ("pro", "Профессиональный"),
                            ("business", "Бизнес"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        max_length=100, verbose_name="Отображаемое название"
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цена в месяц (руб)",
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цена в год (руб)",
                    ),
                ),
                (
                    "daily_limit",
                    models.IntegerField(
                        default=5, verbose_name="Лимит проверок в день"
                    ),
                ),
                (
                    "monthly_limit",
                    models.IntegerField(
                        default=100, verbose_name="Лимит проверок в месяц"
                    ),
                ),
                (
                    "api_access",
                    models.BooleanField(default=False, verbose_name="Доступ к API"),
                ),
                (
                    "bulk_verification",
                    models.BooleanField(
                        default=False, verbose_name="Массовая проверка"
                    ),
                ),
                (
                    "priority_support",
                    models.BooleanField(
                        default=False, verbose_name="Приоритетная поддержка"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "features",
                    models.JSONField(default=list, verbose_name="Список функций"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Тарифный план",
                "verbose_name_plural": "Тарифные планы",
                "ordering": ["price_monthly"],
            },
        ),
        migrations.AddField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="API ключ"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название ключа"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее использование"
                    ),
                ),
                (
                    "requests_count",
                    models.IntegerField(default=0, verbose_name="Количество запросов"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "API ключ",
                "verbose_name_plural": "API ключи",
            },
        ),
        migrations.AddField(
            model_name="emailverification",
            name="api_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="money.apikey",
                verbose_name="API ключ",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("completed", "Оплачен"),
                            ("failed", "Ошибка"),
                            ("refunded", "Возврат"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID платежа"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Способ оплаты"
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("monthly", "Месяц"), ("yearly", "Год")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="money.subscriptionplan",
                        verbose_name="Тарифный план",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_verifications",
                    models.IntegerField(default=0, verbose_name="Проверок сегодня"),
                ),
                (
                    "monthly_verifications",
                    models.IntegerField(
                        default=0, verbose_name="Проверок в этом месяце"
                    ),
                ),
                (
                    "total_verifications",
                    models.IntegerField(default=0, verbose_name="Всего проверок"),
                ),
                (
                    "last_verification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата последней проверки"
                    ),
                ),
                (
                    "subscription_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Начало подписки"
                    ),
                ),
                (
                    "subscription_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание подписки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="money.subscriptionplan",
                        verbose_name="Тарифный план",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
    ]
