# Generated by Django 6.0.1 on 2026-02-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0002_subscriptionplan_emailverification_user_apikey_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YooKassaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Shop ID"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Secret Key"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активен"),
                ),
                (
                    "webhook_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Webhook URL"
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Webhook Secret"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки ЮKassa",
                "verbose_name_plural": "Настройки ЮKassa",
            },
        ),
    ]
